import { CountryList } from "../types/Types";

export const countryList: CountryList[] = [
	{
		name: "Afghanistan",
		alpha2: "AF",
		alpha3: "AFG",
		calling_code: "+93",
		currency_code: "AFN",
		currency_name: "Afghan Afghani",
		symbol: "؋",
		emoji: "🇦🇫",
	},
	{
		name: "Albania",
		alpha2: "AL",
		alpha3: "ALB",
		calling_code: "+355",
		currency_code: "ALL",
		currency_name: "Albanian Lek",
		symbol: "L",
		emoji: "🇦🇱",
	},
	{
		name: "Algeria",
		alpha2: "DZ",
		alpha3: "DZA",
		calling_code: "+213",
		currency_code: "DZD",
		currency_name: "Algerian Dinar",
		symbol: "دج",
		emoji: "🇩🇿",
	},
	{
		name: "Andorra",
		alpha2: "AD",
		alpha3: "AND",
		calling_code: "+376",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇦🇩",
	},
	{
		name: "Angola",
		alpha2: "AO",
		alpha3: "AGO",
		calling_code: "+244",
		currency_code: "AOA",
		currency_name: "Angolan Kwanza",
		symbol: "Kz",
		emoji: "🇦🇴",
	},
	{
		name: "Antigua and Barbuda",
		alpha2: "AG",
		alpha3: "ATG",
		calling_code: "+1268",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇦🇬",
	},
	{
		name: "Argentina",
		alpha2: "AR",
		alpha3: "ARG",
		calling_code: "+54",
		currency_code: "ARS",
		currency_name: "Argentine Peso",
		symbol: "$",
		emoji: "🇦🇷",
	},
	{
		name: "Armenia",
		alpha2: "AM",
		alpha3: "ARM",
		calling_code: "+374",
		currency_code: "AMD",
		currency_name: "Armenian Dram",
		symbol: "֏",
		emoji: "🇦🇲",
	},
	{
		name: "Australia",
		alpha2: "AU",
		alpha3: "AUS",
		calling_code: "+61",
		currency_code: "AUD",
		currency_name: "Australian Dollar",
		symbol: "$",
		emoji: "🇦🇺",
	},
	{
		name: "Austria",
		alpha2: "AT",
		alpha3: "AUT",
		calling_code: "+43",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇦🇹",
	},
	{
		name: "Azerbaijan",
		alpha2: "AZ",
		alpha3: "AZE",
		calling_code: "+994",
		currency_code: "AZN",
		currency_name: "Azerbaijani Manat",
		symbol: "₼",
		emoji: "🇦🇿",
	},
	{
		name: "Bahamas",
		alpha2: "BS",
		alpha3: "BHS",
		calling_code: "+1242",
		currency_code: "BSD",
		currency_name: "Bahamian Dollar",
		symbol: "$",
		emoji: "🇧🇸",
	},
	{
		name: "Bahrain",
		alpha2: "BH",
		alpha3: "BHR",
		calling_code: "+973",
		currency_code: "BHD",
		currency_name: "Bahraini Dinar",
		symbol: "د.ب",
		emoji: "🇧🇭",
	},
	{
		name: "Bangladesh",
		alpha2: "BD",
		alpha3: "BGD",
		calling_code: "+880",
		currency_code: "BDT",
		currency_name: "Bangladeshi Taka",
		symbol: "৳",
		emoji: "🇧🇩",
	},
	{
		name: "Barbados",
		alpha2: "BB",
		alpha3: "BRB",
		calling_code: "+1246",
		currency_code: "BBD",
		currency_name: "Barbadian Dollar",
		symbol: "$",
		emoji: "🇧🇧",
	},
	{
		name: "Belarus",
		alpha2: "BY",
		alpha3: "BLR",
		calling_code: "+375",
		currency_code: "BYN",
		currency_name: "Belarusian Ruble",
		symbol: "Br",
		emoji: "🇧🇾",
	},
	{
		name: "Belgium",
		alpha2: "BE",
		alpha3: "BEL",
		calling_code: "+32",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇧🇪",
	},
	{
		name: "Belize",
		alpha2: "BZ",
		alpha3: "BLZ",
		calling_code: "+501",
		currency_code: "BZD",
		currency_name: "Belize Dollar",
		symbol: "$",
		emoji: "🇧🇿",
	},
	{
		name: "Benin",
		alpha2: "BJ",
		alpha3: "BEN",
		calling_code: "+229",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇧🇯",
	},
	{
		name: "Bhutan",
		alpha2: "BT",
		alpha3: "BTN",
		calling_code: "+975",
		currency_code: "BTN",
		currency_name: "Bhutanese Ngultrum",
		symbol: "Nu.",
		emoji: "🇧🇹",
	},
	{
		name: "Bolivia",
		alpha2: "BO",
		alpha3: "BOL",
		calling_code: "+591",
		currency_code: "BOB",
		currency_name: "Bolivian Boliviano",
		symbol: "Bs.",
		emoji: "🇧🇴",
	},
	{
		name: "Bosnia and Herzegovina",
		alpha2: "BA",
		alpha3: "BIH",
		calling_code: "+387",
		currency_code: "BAM",
		currency_name: "Convertible Mark",
		symbol: "KM",
		emoji: "🇧🇦",
	},
	{
		name: "Botswana",
		alpha2: "BW",
		alpha3: "BWA",
		calling_code: "+267",
		currency_code: "BWP",
		currency_name: "Botswana Pula",
		symbol: "P",
		emoji: "🇧🇼",
	},
	{
		name: "Brazil",
		alpha2: "BR",
		alpha3: "BRA",
		calling_code: "+55",
		currency_code: "BRL",
		currency_name: "Brazilian Real",
		symbol: "R$",
		emoji: "🇧🇷",
	},
	{
		name: "Brunei",
		alpha2: "BN",
		alpha3: "BRN",
		calling_code: "+673",
		currency_code: "BND",
		currency_name: "Brunei Dollar",
		symbol: "$",
		emoji: "🇧🇳",
	},
	{
		name: "Bulgaria",
		alpha2: "BG",
		alpha3: "BGR",
		calling_code: "+359",
		currency_code: "BGN",
		currency_name: "Bulgarian Lev",
		symbol: "лв",
		emoji: "🇧🇬",
	},
	{
		name: "Burkina Faso",
		alpha2: "BF",
		alpha3: "BFA",
		calling_code: "+226",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇧🇫",
	},
	{
		name: "Burundi",
		alpha2: "BI",
		alpha3: "BDI",
		calling_code: "+257",
		currency_code: "BIF",
		currency_name: "Burundian Franc",
		symbol: "Fr",
		emoji: "🇧🇮",
	},
	{
		name: "Cambodia",
		alpha2: "KH",
		alpha3: "KHM",
		calling_code: "+855",
		currency_code: "KHR",
		currency_name: "Cambodian Riel",
		symbol: "៛",
		emoji: "🇰🇭",
	},
	{
		name: "Cameroon",
		alpha2: "CM",
		alpha3: "CMR",
		calling_code: "+237",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇨🇲",
	},
	{
		name: "Canada",
		alpha2: "CA",
		alpha3: "CAN",
		calling_code: "+1",
		currency_code: "CAD",
		currency_name: "Canadian Dollar",
		symbol: "$",
		emoji: "🇨🇦",
	},
	{
		name: "Central African Republic",
		alpha2: "CF",
		alpha3: "CAF",
		calling_code: "+236",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇨🇫",
	},
	{
		name: "Chad",
		alpha2: "TD",
		alpha3: "TCD",
		calling_code: "+235",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇹🇩",
	},
	{
		name: "Chile",
		alpha2: "CL",
		alpha3: "CHL",
		calling_code: "+56",
		currency_code: "CLP",
		currency_name: "Chilean Peso",
		symbol: "$",
		emoji: "🇨🇱",
	},
	{
		name: "China",
		alpha2: "CN",
		alpha3: "CHN",
		calling_code: "+86",
		currency_code: "CNY",
		currency_name: "Chinese Yuan",
		symbol: "¥",
		emoji: "🇨🇳",
	},
	{
		name: "Colombia",
		alpha2: "CO",
		alpha3: "COL",
		calling_code: "+57",
		currency_code: "COP",
		currency_name: "Colombian Peso",
		symbol: "$",
		emoji: "🇨🇴",
	},
	{
		name: "Comoros",
		alpha2: "KM",
		alpha3: "COM",
		calling_code: "+269",
		currency_code: "KMF",
		currency_name: "Comorian Franc",
		symbol: "Fr",
		emoji: "🇰🇲",
	},
	{
		name: "Congo",
		alpha2: "CG",
		alpha3: "COG",
		calling_code: "+242",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇨🇬",
	},
	{
		name: "Costa Rica",
		alpha2: "CR",
		alpha3: "CRI",
		calling_code: "+506",
		currency_code: "CRC",
		currency_name: "Costa Rican Colón",
		symbol: "₡",
		emoji: "🇨🇷",
	},
	{
		name: "Croatia",
		alpha2: "HR",
		alpha3: "HRV",
		calling_code: "+385",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇭🇷",
	},
	{
		name: "Cuba",
		alpha2: "CU",
		alpha3: "CUB",
		calling_code: "+53",
		currency_code: "CUP",
		currency_name: "Cuban Peso",
		symbol: "$",
		emoji: "🇨🇺",
	},
	{
		name: "Cyprus",
		alpha2: "CY",
		alpha3: "CYP",
		calling_code: "+357",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇨🇾",
	},
	{
		name: "Czech Republic",
		alpha2: "CZ",
		alpha3: "CZE",
		calling_code: "+420",
		currency_code: "CZK",
		currency_name: "Czech Koruna",
		symbol: "Kč",
		emoji: "🇨🇿",
	},
	{
		name: "Denmark",
		alpha2: "DK",
		alpha3: "DNK",
		calling_code: "+45",
		currency_code: "DKK",
		currency_name: "Danish Krone",
		symbol: "kr",
		emoji: "🇩🇰",
	},
	{
		name: "Djibouti",
		alpha2: "DJ",
		alpha3: "DJI",
		calling_code: "+253",
		currency_code: "DJF",
		currency_name: "Djiboutian Franc",
		symbol: "Fr",
		emoji: "🇩🇯",
	},
	{
		name: "Dominica",
		alpha2: "DM",
		alpha3: "DMA",
		calling_code: "+1767",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇩🇲",
	},
	{
		name: "Dominican Republic",
		alpha2: "DO",
		alpha3: "DOM",
		calling_code: "+1809",
		currency_code: "DOP",
		currency_name: "Dominican Peso",
		symbol: "$",
		emoji: "🇩🇴",
	},
	{
		name: "Ecuador",
		alpha2: "EC",
		alpha3: "ECU",
		calling_code: "+593",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇪🇨",
	},
	{
		name: "Egypt",
		alpha2: "EG",
		alpha3: "EGY",
		calling_code: "+20",
		currency_code: "EGP",
		currency_name: "Egyptian Pound",
		symbol: "£",
		emoji: "🇪🇬",
	},
	{
		name: "El Salvador",
		alpha2: "SV",
		alpha3: "SLV",
		calling_code: "+503",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇸🇻",
	},
	{
		name: "Equatorial Guinea",
		alpha2: "GQ",
		alpha3: "GNQ",
		calling_code: "+240",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇬🇶",
	},
	{
		name: "Eritrea",
		alpha2: "ER",
		alpha3: "ERI",
		calling_code: "+291",
		currency_code: "ERN",
		currency_name: "Eritrean Nakfa",
		symbol: "Nfk",
		emoji: "🇪🇷",
	},
	{
		name: "Estonia",
		alpha2: "EE",
		alpha3: "EST",
		calling_code: "+372",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇪🇪",
	},
	{
		name: "Eswatini",
		alpha2: "SZ",
		alpha3: "SWZ",
		calling_code: "+268",
		currency_code: "SZL",
		currency_name: "Swazi Lilangeni",
		symbol: "L",
		emoji: "🇸🇿",
	},
	{
		name: "Ethiopia",
		alpha2: "ET",
		alpha3: "ETH",
		calling_code: "+251",
		currency_code: "ETB",
		currency_name: "Ethiopian Birr",
		symbol: "Br",
		emoji: "🇪🇹",
	},
	{
		name: "Fiji",
		alpha2: "FJ",
		alpha3: "FJI",
		calling_code: "+679",
		currency_code: "FJD",
		currency_name: "Fijian Dollar",
		symbol: "$",
		emoji: "🇫🇯",
	},
	{
		name: "Finland",
		alpha2: "FI",
		alpha3: "FIN",
		calling_code: "+358",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇫🇮",
	},
	{
		name: "France",
		alpha2: "FR",
		alpha3: "FRA",
		calling_code: "+33",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇫🇷",
	},
	{
		name: "Gabon",
		alpha2: "GA",
		alpha3: "GAB",
		calling_code: "+241",
		currency_code: "XAF",
		currency_name: "Central African CFA Franc",
		symbol: "CFA",
		emoji: "🇬🇦",
	},
	{
		name: "Gambia",
		alpha2: "GM",
		alpha3: "GMB",
		calling_code: "+220",
		currency_code: "GMD",
		currency_name: "Gambian Dalasi",
		symbol: "D",
		emoji: "🇬🇲",
	},
	{
		name: "Georgia",
		alpha2: "GE",
		alpha3: "GEO",
		calling_code: "+995",
		currency_code: "GEL",
		currency_name: "Georgian Lari",
		symbol: "₾",
		emoji: "🇬🇪",
	},
	{
		name: "Germany",
		alpha2: "DE",
		alpha3: "DEU",
		calling_code: "+49",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇩🇪",
	},
	{
		name: "Ghana",
		alpha2: "GH",
		alpha3: "GHA",
		calling_code: "+233",
		currency_code: "GHS",
		currency_name: "Ghanaian Cedi",
		symbol: "₵",
		emoji: "🇬🇭",
	},
	{
		name: "Greece",
		alpha2: "GR",
		alpha3: "GRC",
		calling_code: "+30",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇬🇷",
	},
	{
		name: "Grenada",
		alpha2: "GD",
		alpha3: "GRD",
		calling_code: "+1473",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇬🇩",
	},
	{
		name: "Guatemala",
		alpha2: "GT",
		alpha3: "GTM",
		calling_code: "+502",
		currency_code: "GTQ",
		currency_name: "Guatemalan Quetzal",
		symbol: "Q",
		emoji: "🇬🇹",
	},
	{
		name: "Guinea",
		alpha2: "GN",
		alpha3: "GIN",
		calling_code: "+224",
		currency_code: "GNF",
		currency_name: "Guinean Franc",
		symbol: "Fr",
		emoji: "🇬🇳",
	},
	{
		name: "Guinea-Bissau",
		alpha2: "GW",
		alpha3: "GNB",
		calling_code: "+245",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇬🇼",
	},
	{
		name: "Guyana",
		alpha2: "GY",
		alpha3: "GUY",
		calling_code: "+592",
		currency_code: "GYD",
		currency_name: "Guyanese Dollar",
		symbol: "$",
		emoji: "🇬🇾",
	},
	{
		name: "Haiti",
		alpha2: "HT",
		alpha3: "HTI",
		calling_code: "+509",
		currency_code: "HTG",
		currency_name: "Haitian Gourde",
		symbol: "G",
		emoji: "🇭🇹",
	},
	{
		name: "Honduras",
		alpha2: "HN",
		alpha3: "HND",
		calling_code: "+504",
		currency_code: "HNL",
		currency_name: "Honduran Lempira",
		symbol: "L",
		emoji: "🇭🇳",
	},
	{
		name: "Hungary",
		alpha2: "HU",
		alpha3: "HUN",
		calling_code: "+36",
		currency_code: "HUF",
		currency_name: "Hungarian Forint",
		symbol: "Ft",
		emoji: "🇭🇺",
	},
	{
		name: "Iceland",
		alpha2: "IS",
		alpha3: "ISL",
		calling_code: "+354",
		currency_code: "ISK",
		currency_name: "Icelandic Króna",
		symbol: "kr",
		emoji: "🇮🇸",
	},
	{
		name: "India",
		alpha2: "IN",
		alpha3: "IND",
		calling_code: "+91",
		currency_code: "INR",
		currency_name: "Indian Rupee",
		symbol: "₹",
		emoji: "🇮🇳",
	},
	{
		name: "Indonesia",
		alpha2: "ID",
		alpha3: "IDN",
		calling_code: "+62",
		currency_code: "IDR",
		currency_name: "Indonesian Rupiah",
		symbol: "Rp",
		emoji: "🇮🇩",
	},
	{
		name: "Iran",
		alpha2: "IR",
		alpha3: "IRN",
		calling_code: "+98",
		currency_code: "IRR",
		currency_name: "Iranian Rial",
		symbol: "﷼",
		emoji: "🇮🇷",
	},
	{
		name: "Iraq",
		alpha2: "IQ",
		alpha3: "IRQ",
		calling_code: "+964",
		currency_code: "IQD",
		currency_name: "Iraqi Dinar",
		symbol: "ع.د",
		emoji: "🇮🇶",
	},
	{
		name: "Ireland",
		alpha2: "IE",
		alpha3: "IRL",
		calling_code: "+353",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇮🇪",
	},
	{
		name: "Israel",
		alpha2: "IL",
		alpha3: "ISR",
		calling_code: "+972",
		currency_code: "ILS",
		currency_name: "Israeli New Shekel",
		symbol: "₪",
		emoji: "🇮🇱",
	},
	{
		name: "Italy",
		alpha2: "IT",
		alpha3: "ITA",
		calling_code: "+39",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇮🇹",
	},
	{
		name: "Jamaica",
		alpha2: "JM",
		alpha3: "JAM",
		calling_code: "+1876",
		currency_code: "JMD",
		currency_name: "Jamaican Dollar",
		symbol: "$",
		emoji: "🇯🇲",
	},
	{
		name: "Japan",
		alpha2: "JP",
		alpha3: "JPN",
		calling_code: "+81",
		currency_code: "JPY",
		currency_name: "Japanese Yen",
		symbol: "¥",
		emoji: "🇯🇵",
	},
	{
		name: "Jordan",
		alpha2: "JO",
		alpha3: "JOR",
		calling_code: "+962",
		currency_code: "JOD",
		currency_name: "Jordanian Dinar",
		symbol: "د.ا",
		emoji: "🇯🇴",
	},
	{
		name: "Kazakhstan",
		alpha2: "KZ",
		alpha3: "KAZ",
		calling_code: "+7",
		currency_code: "KZT",
		currency_name: "Kazakhstani Tenge",
		symbol: "₸",
		emoji: "🇰🇿",
	},
	{
		name: "Kenya",
		alpha2: "KE",
		alpha3: "KEN",
		calling_code: "+254",
		currency_code: "KES",
		currency_name: "Kenyan Shilling",
		symbol: "Sh",
		emoji: "🇰🇪",
	},
	{
		name: "Kiribati",
		alpha2: "KI",
		alpha3: "KIR",
		calling_code: "+686",
		currency_code: "AUD",
		currency_name: "Australian Dollar",
		symbol: "$",
		emoji: "🇰🇮",
	},
	{
		name: "Kuwait",
		alpha2: "KW",
		alpha3: "KWT",
		calling_code: "+965",
		currency_code: "KWD",
		currency_name: "Kuwaiti Dinar",
		symbol: "د.ك",
		emoji: "🇰🇼",
	},
	{
		name: "Kyrgyzstan",
		alpha2: "KG",
		alpha3: "KGZ",
		calling_code: "+996",
		currency_code: "KGS",
		currency_name: "Kyrgyzstani Som",
		symbol: "с",
		emoji: "🇰🇬",
	},
	{
		name: "Laos",
		alpha2: "LA",
		alpha3: "LAO",
		calling_code: "+856",
		currency_code: "LAK",
		currency_name: "Lao Kip",
		symbol: "₭",
		emoji: "🇱🇦",
	},
	{
		name: "Latvia",
		alpha2: "LV",
		alpha3: "LVA",
		calling_code: "+371",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇱🇻",
	},
	{
		name: "Lebanon",
		alpha2: "LB",
		alpha3: "LBN",
		calling_code: "+961",
		currency_code: "LBP",
		currency_name: "Lebanese Pound",
		symbol: "ل.ل",
		emoji: "🇱🇧",
	},
	{
		name: "Lesotho",
		alpha2: "LS",
		alpha3: "LSO",
		calling_code: "+266",
		currency_code: "LSL",
		currency_name: "Lesotho Loti",
		symbol: "L",
		emoji: "🇱🇸",
	},
	{
		name: "Liberia",
		alpha2: "LR",
		alpha3: "LBR",
		calling_code: "+231",
		currency_code: "LRD",
		currency_name: "Liberian Dollar",
		symbol: "$",
		emoji: "🇱🇷",
	},
	{
		name: "Libya",
		alpha2: "LY",
		alpha3: "LBY",
		calling_code: "+218",
		currency_code: "LYD",
		currency_name: "Libyan Dinar",
		symbol: "ل.د",
		emoji: "🇱🇾",
	},
	{
		name: "Liechtenstein",
		alpha2: "LI",
		alpha3: "LIE",
		calling_code: "+423",
		currency_code: "CHF",
		currency_name: "Swiss Franc",
		symbol: "Fr",
		emoji: "🇱🇮",
	},
	{
		name: "Lithuania",
		alpha2: "LT",
		alpha3: "LTU",
		calling_code: "+370",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇱🇹",
	},
	{
		name: "Luxembourg",
		alpha2: "LU",
		alpha3: "LUX",
		calling_code: "+352",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇱🇺",
	},
	{
		name: "Madagascar",
		alpha2: "MG",
		alpha3: "MDG",
		calling_code: "+261",
		currency_code: "MGA",
		currency_name: "Malagasy Ariary",
		symbol: "Ar",
		emoji: "🇲🇬",
	},
	{
		name: "Malawi",
		alpha2: "MW",
		alpha3: "MWI",
		calling_code: "+265",
		currency_code: "MWK",
		currency_name: "Malawian Kwacha",
		symbol: "MK",
		emoji: "🇲🇼",
	},
	{
		name: "Malaysia",
		alpha2: "MY",
		alpha3: "MYS",
		calling_code: "+60",
		currency_code: "MYR",
		currency_name: "Malaysian Ringgit",
		symbol: "RM",
		emoji: "🇲🇾",
	},
	{
		name: "Maldives",
		alpha2: "MV",
		alpha3: "MDV",
		calling_code: "+960",
		currency_code: "MVR",
		currency_name: "Maldivian Rufiyaa",
		symbol: "Rf",
		emoji: "🇲🇻",
	},
	{
		name: "Mali",
		alpha2: "ML",
		alpha3: "MLI",
		calling_code: "+223",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇲🇱",
	},
	{
		name: "Malta",
		alpha2: "MT",
		alpha3: "MLT",
		calling_code: "+356",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇲🇹",
	},
	{
		name: "Marshall Islands",
		alpha2: "MH",
		alpha3: "MHL",
		calling_code: "+692",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇲🇭",
	},
	{
		name: "Mauritania",
		alpha2: "MR",
		alpha3: "MRT",
		calling_code: "+222",
		currency_code: "MRU",
		currency_name: "Mauritanian Ouguiya",
		symbol: "UM",
		emoji: "🇲🇷",
	},
	{
		name: "Mauritius",
		alpha2: "MU",
		alpha3: "MUS",
		calling_code: "+230",
		currency_code: "MUR",
		currency_name: "Mauritian Rupee",
		symbol: "₨",
		emoji: "🇲🇺",
	},
	{
		name: "Mexico",
		alpha2: "MX",
		alpha3: "MEX",
		calling_code: "+52",
		currency_code: "MXN",
		currency_name: "Mexican Peso",
		symbol: "$",
		emoji: "🇲🇽",
	},
	{
		name: "Micronesia",
		alpha2: "FM",
		alpha3: "FSM",
		calling_code: "+691",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇫🇲",
	},
	{
		name: "Moldova",
		alpha2: "MD",
		alpha3: "MDA",
		calling_code: "+373",
		currency_code: "MDL",
		currency_name: "Moldovan Leu",
		symbol: "L",
		emoji: "🇲🇩",
	},
	{
		name: "Monaco",
		alpha2: "MC",
		alpha3: "MCO",
		calling_code: "+377",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇲🇨",
	},
	{
		name: "Mongolia",
		alpha2: "MN",
		alpha3: "MNG",
		calling_code: "+976",
		currency_code: "MNT",
		currency_name: "Mongolian Tögrög",
		symbol: "₮",
		emoji: "🇲🇳",
	},
	{
		name: "Montenegro",
		alpha2: "ME",
		alpha3: "MNE",
		calling_code: "+382",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇲🇪",
	},
	{
		name: "Morocco",
		alpha2: "MA",
		alpha3: "MAR",
		calling_code: "+212",
		currency_code: "MAD",
		currency_name: "Moroccan Dirham",
		symbol: "د.م.",
		emoji: "🇲🇦",
	},
	{
		name: "Mozambique",
		alpha2: "MZ",
		alpha3: "MOZ",
		calling_code: "+258",
		currency_code: "MZN",
		currency_name: "Mozambican Metical",
		symbol: "MT",
		emoji: "🇲🇿",
	},
	{
		name: "Myanmar",
		alpha2: "MM",
		alpha3: "MMR",
		calling_code: "+95",
		currency_code: "MMK",
		currency_name: "Burmese Kyat",
		symbol: "Ks",
		emoji: "🇲🇲",
	},
	{
		name: "Namibia",
		alpha2: "NA",
		alpha3: "NAM",
		calling_code: "+264",
		currency_code: "NAD",
		currency_name: "Namibian Dollar",
		symbol: "$",
		emoji: "🇳🇦",
	},
	{
		name: "Nauru",
		alpha2: "NR",
		alpha3: "NRU",
		calling_code: "+674",
		currency_code: "AUD",
		currency_name: "Australian Dollar",
		symbol: "$",
		emoji: "🇳🇷",
	},
	{
		name: "Nepal",
		alpha2: "NP",
		alpha3: "NPL",
		calling_code: "+977",
		currency_code: "NPR",
		currency_name: "Nepalese Rupee",
		symbol: "₨",
		emoji: "🇳🇵",
	},
	{
		name: "Netherlands",
		alpha2: "NL",
		alpha3: "NLD",
		calling_code: "+31",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇳🇱",
	},
	{
		name: "New Zealand",
		alpha2: "NZ",
		alpha3: "NZL",
		calling_code: "+64",
		currency_code: "NZD",
		currency_name: "New Zealand Dollar",
		symbol: "$",
		emoji: "🇳🇿",
	},
	{
		name: "Nicaragua",
		alpha2: "NI",
		alpha3: "NIC",
		calling_code: "+505",
		currency_code: "NIO",
		currency_name: "Nicaraguan Córdoba",
		symbol: "C$",
		emoji: "🇳🇮",
	},
	{
		name: "Niger",
		alpha2: "NE",
		alpha3: "NER",
		calling_code: "+227",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇳🇪",
	},
	{
		name: "Nigeria",
		alpha2: "NG",
		alpha3: "NGA",
		calling_code: "+234",
		currency_code: "NGN",
		currency_name: "Nigerian Naira",
		symbol: "₦",
		emoji: "🇳🇬",
	},
	{
		name: "North Korea",
		alpha2: "KP",
		alpha3: "PRK",
		calling_code: "+850",
		currency_code: "KPW",
		currency_name: "North Korean Won",
		symbol: "₩",
		emoji: "🇰🇵",
	},
	{
		name: "North Macedonia",
		alpha2: "MK",
		alpha3: "MKD",
		calling_code: "+389",
		currency_code: "MKD",
		currency_name: "Macedonian Denar",
		symbol: "ден",
		emoji: "🇲🇰",
	},
	{
		name: "Norway",
		alpha2: "NO",
		alpha3: "NOR",
		calling_code: "+47",
		currency_code: "NOK",
		currency_name: "Norwegian Krone",
		symbol: "kr",
		emoji: "🇳🇴",
	},
	{
		name: "Oman",
		alpha2: "OM",
		alpha3: "OMN",
		calling_code: "+968",
		currency_code: "OMR",
		currency_name: "Omani Rial",
		symbol: "ر.ع.",
		emoji: "🇴🇲",
	},
	{
		name: "Pakistan",
		alpha2: "PK",
		alpha3: "PAK",
		calling_code: "+92",
		currency_code: "PKR",
		currency_name: "Pakistani Rupee",
		symbol: "₨",
		emoji: "🇵🇰",
	},
	{
		name: "Palau",
		alpha2: "PW",
		alpha3: "PLW",
		calling_code: "+680",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇵🇼",
	},
	{
		name: "Palestine",
		alpha2: "PS",
		alpha3: "PSE",
		calling_code: "+970",
		currency_code: "ILS",
		currency_name: "Israeli New Shekel",
		symbol: "₪",
		emoji: "🇵🇸",
	},
	{
		name: "Panama",
		alpha2: "PA",
		alpha3: "PAN",
		calling_code: "+507",
		currency_code: "PAB",
		currency_name: "Panamanian Balboa",
		symbol: "B/.",
		emoji: "🇵🇦",
	},
	{
		name: "Papua New Guinea",
		alpha2: "PG",
		alpha3: "PNG",
		calling_code: "+675",
		currency_code: "PGK",
		currency_name: "Papua New Guinean Kina",
		symbol: "K",
		emoji: "🇵🇬",
	},
	{
		name: "Paraguay",
		alpha2: "PY",
		alpha3: "PRY",
		calling_code: "+595",
		currency_code: "PYG",
		currency_name: "Paraguayan Guaraní",
		symbol: "₲",
		emoji: "🇵🇾",
	},
	{
		name: "Peru",
		alpha2: "PE",
		alpha3: "PER",
		calling_code: "+51",
		currency_code: "PEN",
		currency_name: "Peruvian Sol",
		symbol: "S/.",
		emoji: "🇵🇪",
	},
	{
		name: "Philippines",
		alpha2: "PH",
		alpha3: "PHL",
		calling_code: "+63",
		currency_code: "PHP",
		currency_name: "Philippine Peso",
		symbol: "₱",
		emoji: "🇵🇭",
	},
	{
		name: "Poland",
		alpha2: "PL",
		alpha3: "POL",
		calling_code: "+48",
		currency_code: "PLN",
		currency_name: "Polish Złoty",
		symbol: "zł",
		emoji: "🇵🇱",
	},
	{
		name: "Portugal",
		alpha2: "PT",
		alpha3: "PRT",
		calling_code: "+351",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇵🇹",
	},
	{
		name: "Qatar",
		alpha2: "QA",
		alpha3: "QAT",
		calling_code: "+974",
		currency_code: "QAR",
		currency_name: "Qatari Riyal",
		symbol: "ر.ق",
		emoji: "🇶🇦",
	},
	{
		name: "Romania",
		alpha2: "RO",
		alpha3: "ROU",
		calling_code: "+40",
		currency_code: "RON",
		currency_name: "Romanian Leu",
		symbol: "lei",
		emoji: "🇷🇴",
	},
	{
		name: "Russia",
		alpha2: "RU",
		alpha3: "RUS",
		calling_code: "+7",
		currency_code: "RUB",
		currency_name: "Russian Ruble",
		symbol: "₽",
		emoji: "🇷🇺",
	},
	{
		name: "Rwanda",
		alpha2: "RW",
		alpha3: "RWA",
		calling_code: "+250",
		currency_code: "RWF",
		currency_name: "Rwandan Franc",
		symbol: "Fr",
		emoji: "🇷🇼",
	},
	{
		name: "Saint Kitts and Nevis",
		alpha2: "KN",
		alpha3: "KNA",
		calling_code: "+1869",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇰🇳",
	},
	{
		name: "Saint Lucia",
		alpha2: "LC",
		alpha3: "LCA",
		calling_code: "+1758",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇱🇨",
	},
	{
		name: "Saint Vincent and the Grenadines",
		alpha2: "VC",
		alpha3: "VCT",
		calling_code: "+1784",
		currency_code: "XCD",
		currency_name: "East Caribbean Dollar",
		symbol: "$",
		emoji: "🇻🇨",
	},
	{
		name: "Samoa",
		alpha2: "WS",
		alpha3: "WSM",
		calling_code: "+685",
		currency_code: "WST",
		currency_name: "Samoan Tala",
		symbol: "T",
		emoji: "🇼🇸",
	},
	{
		name: "San Marino",
		alpha2: "SM",
		alpha3: "SMR",
		calling_code: "+378",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇸🇲",
	},
	{
		name: "Sao Tome and Principe",
		alpha2: "ST",
		alpha3: "STP",
		calling_code: "+239",
		currency_code: "STN",
		currency_name: "São Tomé and Príncipe Dobra",
		symbol: "Db",
		emoji: "🇸🇹",
	},
	{
		name: "Saudi Arabia",
		alpha2: "SA",
		alpha3: "SAU",
		calling_code: "+966",
		currency_code: "SAR",
		currency_name: "Saudi Riyal",
		symbol: "ر.س",
		emoji: "🇸🇦",
	},
	{
		name: "Senegal",
		alpha2: "SN",
		alpha3: "SEN",
		calling_code: "+221",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇸🇳",
	},
	{
		name: "Serbia",
		alpha2: "RS",
		alpha3: "SRB",
		calling_code: "+381",
		currency_code: "RSD",
		currency_name: "Serbian Dinar",
		symbol: "дин.",
		emoji: "🇷🇸",
	},
	{
		name: "Seychelles",
		alpha2: "SC",
		alpha3: "SYC",
		calling_code: "+248",
		currency_code: "SCR",
		currency_name: "Seychellois Rupee",
		symbol: "₨",
		emoji: "🇸🇨",
	},
	{
		name: "Sierra Leone",
		alpha2: "SL",
		alpha3: "SLE",
		calling_code: "+232",
		currency_code: "SLL",
		currency_name: "Sierra Leonean Leone",
		symbol: "Le",
		emoji: "🇸🇱",
	},
	{
		name: "Singapore",
		alpha2: "SG",
		alpha3: "SGP",
		calling_code: "+65",
		currency_code: "SGD",
		currency_name: "Singapore Dollar",
		symbol: "$",
		emoji: "🇸🇬",
	},
	{
		name: "Slovakia",
		alpha2: "SK",
		alpha3: "SVK",
		calling_code: "+421",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇸🇰",
	},
	{
		name: "Slovenia",
		alpha2: "SI",
		alpha3: "SVN",
		calling_code: "+386",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇸🇮",
	},
	{
		name: "Solomon Islands",
		alpha2: "SB",
		alpha3: "SLB",
		calling_code: "+677",
		currency_code: "SBD",
		currency_name: "Solomon Islands Dollar",
		symbol: "$",
		emoji: "🇸🇧",
	},
	{
		name: "Somalia",
		alpha2: "SO",
		alpha3: "SOM",
		calling_code: "+252",
		currency_code: "SOS",
		currency_name: "Somali Shilling",
		symbol: "Sh",
		emoji: "🇸🇴",
	},
	{
		name: "South Africa",
		alpha2: "ZA",
		alpha3: "ZAF",
		calling_code: "+27",
		currency_code: "ZAR",
		currency_name: "South African Rand",
		symbol: "R",
		emoji: "🇿🇦",
	},
	{
		name: "South Korea",
		alpha2: "KR",
		alpha3: "KOR",
		calling_code: "+82",
		currency_code: "KRW",
		currency_name: "South Korean Won",
		symbol: "₩",
		emoji: "🇰🇷",
	},
	{
		name: "South Sudan",
		alpha2: "SS",
		alpha3: "SSD",
		calling_code: "+211",
		currency_code: "SSP",
		currency_name: "South Sudanese Pound",
		symbol: "£",
		emoji: "🇸🇸",
	},
	{
		name: "Spain",
		alpha2: "ES",
		alpha3: "ESP",
		calling_code: "+34",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇪🇸",
	},
	{
		name: "Sri Lanka",
		alpha2: "LK",
		alpha3: "LKA",
		calling_code: "+94",
		currency_code: "LKR",
		currency_name: "Sri Lankan Rupee",
		symbol: "₨",
		emoji: "🇱🇰",
	},
	{
		name: "Sudan",
		alpha2: "SD",
		alpha3: "SDN",
		calling_code: "+249",
		currency_code: "SDG",
		currency_name: "Sudanese Pound",
		symbol: "£",
		emoji: "🇸🇩",
	},
	{
		name: "Suriname",
		alpha2: "SR",
		alpha3: "SUR",
		calling_code: "+597",
		currency_code: "SRD",
		currency_name: "Surinamese Dollar",
		symbol: "$",
		emoji: "🇸🇷",
	},
	{
		name: "Sweden",
		alpha2: "SE",
		alpha3: "SWE",
		calling_code: "+46",
		currency_code: "SEK",
		currency_name: "Swedish Krona",
		symbol: "kr",
		emoji: "🇸🇪",
	},
	{
		name: "Switzerland",
		alpha2: "CH",
		alpha3: "CHE",
		calling_code: "+41",
		currency_code: "CHF",
		currency_name: "Swiss Franc",
		symbol: "Fr",
		emoji: "🇨🇭",
	},
	{
		name: "Syria",
		alpha2: "SY",
		alpha3: "SYR",
		calling_code: "+963",
		currency_code: "SYP",
		currency_name: "Syrian Pound",
		symbol: "£",
		emoji: "🇸🇾",
	},
	{
		name: "Taiwan",
		alpha2: "TW",
		alpha3: "TWN",
		calling_code: "+886",
		currency_code: "TWD",
		currency_name: "New Taiwan Dollar",
		symbol: "$",
		emoji: "🇹🇼",
	},
	{
		name: "Tajikistan",
		alpha2: "TJ",
		alpha3: "TJK",
		calling_code: "+992",
		currency_code: "TJS",
		currency_name: "Tajikistani Somoni",
		symbol: "ЅМ",
		emoji: "🇹🇯",
	},
	{
		name: "Tanzania",
		alpha2: "TZ",
		alpha3: "TZA",
		calling_code: "+255",
		currency_code: "TZS",
		currency_name: "Tanzanian Shilling",
		symbol: "Sh",
		emoji: "🇹🇿",
	},
	{
		name: "Thailand",
		alpha2: "TH",
		alpha3: "THA",
		calling_code: "+66",
		currency_code: "THB",
		currency_name: "Thai Baht",
		symbol: "฿",
		emoji: "🇹🇭",
	},
	{
		name: "Timor-Leste",
		alpha2: "TL",
		alpha3: "TLS",
		calling_code: "+670",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇹🇱",
	},
	{
		name: "Togo",
		alpha2: "TG",
		alpha3: "TGO",
		calling_code: "+228",
		currency_code: "XOF",
		currency_name: "West African CFA Franc",
		symbol: "CFA",
		emoji: "🇹🇬",
	},
	{
		name: "Tonga",
		alpha2: "TO",
		alpha3: "TON",
		calling_code: "+676",
		currency_code: "TOP",
		currency_name: "Tongan Paʻanga",
		symbol: "T$",
		emoji: "🇹🇴",
	},
	{
		name: "Trinidad and Tobago",
		alpha2: "TT",
		alpha3: "TTO",
		calling_code: "+1868",
		currency_code: "TTD",
		currency_name: "Trinidad and Tobago Dollar",
		symbol: "$",
		emoji: "🇹🇹",
	},
	{
		name: "Tunisia",
		alpha2: "TN",
		alpha3: "TUN",
		calling_code: "+216",
		currency_code: "TND",
		currency_name: "Tunisian Dinar",
		symbol: "د.ت",
		emoji: "🇹🇳",
	},
	{
		name: "Turkey",
		alpha2: "TR",
		alpha3: "TUR",
		calling_code: "+90",
		currency_code: "TRY",
		currency_name: "Turkish Lira",
		symbol: "₺",
		emoji: "🇹🇷",
	},
	{
		name: "Turkmenistan",
		alpha2: "TM",
		alpha3: "TKM",
		calling_code: "+993",
		currency_code: "TMT",
		currency_name: "Turkmenistan Manat",
		symbol: "m",
		emoji: "🇹🇲",
	},
	{
		name: "Tuvalu",
		alpha2: "TV",
		alpha3: "TUV",
		calling_code: "+688",
		currency_code: "AUD",
		currency_name: "Australian Dollar",
		symbol: "$",
		emoji: "🇹🇻",
	},
	{
		name: "Uganda",
		alpha2: "UG",
		alpha3: "UGA",
		calling_code: "+256",
		currency_code: "UGX",
		currency_name: "Ugandan Shilling",
		symbol: "Sh",
		emoji: "🇺🇬",
	},
	{
		name: "Ukraine",
		alpha2: "UA",
		alpha3: "UKR",
		calling_code: "+380",
		currency_code: "UAH",
		currency_name: "Ukrainian Hryvnia",
		symbol: "₴",
		emoji: "🇺🇦",
	},
	{
		name: "United Arab Emirates",
		alpha2: "AE",
		alpha3: "ARE",
		calling_code: "+971",
		currency_code: "AED",
		currency_name: "United Arab Emirates Dirham",
		symbol: "د.إ",
		emoji: "🇦🇪",
	},
	{
		name: "United Kingdom",
		alpha2: "GB",
		alpha3: "GBR",
		calling_code: "+44",
		currency_code: "GBP",
		currency_name: "British Pound",
		symbol: "£",
		emoji: "🇬🇧",
	},
	{
		name: "United States",
		alpha2: "US",
		alpha3: "USA",
		calling_code: "+1",
		currency_code: "USD",
		currency_name: "United States Dollar",
		symbol: "$",
		emoji: "🇺🇸",
	},
	{
		name: "Uruguay",
		alpha2: "UY",
		alpha3: "URY",
		calling_code: "+598",
		currency_code: "UYU",
		currency_name: "Uruguayan Peso",
		symbol: "$",
		emoji: "🇺🇾",
	},
	{
		name: "Uzbekistan",
		alpha2: "UZ",
		alpha3: "UZB",
		calling_code: "+998",
		currency_code: "UZS",
		currency_name: "Uzbekistani Som",
		symbol: "сўм",
		emoji: "🇺🇿",
	},
	{
		name: "Vanuatu",
		alpha2: "VU",
		alpha3: "VUT",
		calling_code: "+678",
		currency_code: "VUV",
		currency_name: "Vanuatu Vatu",
		symbol: "VT",
		emoji: "🇻🇺",
	},
	{
		name: "Vatican City",
		alpha2: "VA",
		alpha3: "VAT",
		calling_code: "+379",
		currency_code: "EUR",
		currency_name: "Euro",
		symbol: "€",
		emoji: "🇻🇦",
	},
	{
		name: "Venezuela",
		alpha2: "VE",
		alpha3: "VEN",
		calling_code: "+58",
		currency_code: "VES",
		currency_name: "Venezuelan Bolívar",
		symbol: "Bs.S",
		emoji: "🇻🇪",
	},
	{
		name: "Vietnam",
		alpha2: "VN",
		alpha3: "VNM",
		calling_code: "+84",
		currency_code: "VND",
		currency_name: "Vietnamese đồng",
		symbol: "₫",
		emoji: "🇻🇳",
	},
	{
		name: "Yemen",
		alpha2: "YE",
		alpha3: "YEM",
		calling_code: "+967",
		currency_code: "YER",
		currency_name: "Yemeni Rial",
		symbol: "﷼",
		emoji: "🇾🇪",
	},
	{
		name: "Zambia",
		alpha2: "ZM",
		alpha3: "ZMB",
		calling_code: "+260",
		currency_code: "ZMW",
		currency_name: "Zambian Kwacha",
		symbol: "ZK",
		emoji: "🇿🇲",
	},
	{
		name: "Zimbabwe",
		alpha2: "ZW",
		alpha3: "ZWE",
		calling_code: "+263",
		currency_code: "ZWL",
		currency_name: "Zimbabwean Dollar",
		symbol: "$",
		emoji: "🇿🇼",
	},
];
